stages:
  - build
  - test
  - deploy

variables:
  MYSQL_DATABASE: drupal
  MYSQL_USER: drupal
  MYSQL_PASSWORD: drupal
  MYSQL_ROOT_PASSWORD: root

cache:
  paths:
    - vendor/
    - web/core
    - web/modules/contrib
    - web/themes/contrib

build:
  stage: build
  image: php:8.2
  script:
    - apt-get update && apt-get install -y git unzip mariadb-client
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install --prefer-dist --no-interaction

test:
  stage: test
  image: php:8.2
  services:
    - mysql:5.7
  script:
    - vendor/bin/phpunit --configuration core/phpunit.xml.dist

deploy:
  stage: deploy
  script:
    - echo "Aquí se agrega el script de despliegue (rsync, ssh, Acquia, Pantheon, etc.)"
  only:
    - main
