<?php

/**
 * @file
 * Paragraph_conditional_fields.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_form_alter().
 */
function paragraph_conditional_fields_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (strpos($form_id, 'node_') === 0 && strpos($form_id, '_form') !== FALSE) {
    _paragraph_conditional_fields_add_js($form);
  }

  if (strpos($form_id, 'layout_paragraphs_component_form') === 0) {
    _paragraph_conditional_fields_add_js($form);
  }

  if (strpos($form_id, 'paragraph_') === 0 && strpos($form_id, '_form') !== FALSE) {
    _paragraph_conditional_fields_add_js($form);
  }
}

/**
 * Agrega JavaScript personalizado para manejar las dependencias.
 */
function _paragraph_conditional_fields_add_js(&$form) {
  $config = \Drupal::config('paragraph_conditional_fields.settings');
  $dependencies = $config->get('dependencies') ?: [];

  if (!empty($dependencies)) {
    $form['#attached']['library'][] = 'paragraph_conditional_fields/conditional_logic';
    $form['#attached']['drupalSettings']['paragraph_conditional_fields'] = $dependencies;
  }

  $form['#attached']['library'][] = 'paragraph_conditional_fields/card_tarjeta_specific';
}

/**
 * Implements hook_entity_view_alter().
 */
function paragraph_conditional_fields_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {

  if ($entity->getEntityTypeId() == 'paragraph') {
    $config = \Drupal::config('paragraph_conditional_fields.settings');
    $dependencies = $config->get('dependencies') ?: [];

    foreach ($dependencies as $dependency) {
      if ($dependency['child_paragraph_type'] == $entity->bundle()) {
        _paragraph_conditional_fields_process_view($build, $entity, $dependency);
      }
    }
  }
}

/**
 * Procesa las dependencias en la vista.
 */
function _paragraph_conditional_fields_process_view(&$build, $entity, $dependency) {
  $parent = $entity->getParentEntity();

  if ($parent && $parent->hasField($dependency['parent_field'])) {
    $parent_value = $parent->get($dependency['parent_field'])->value;

    if ($parent_value == $dependency['trigger_value']) {

      if (isset($build[$dependency['dependent_field']])) {
        $build[$dependency['dependent_field']]['#access'] = FALSE;
      }
    }
  }
}
