# Schema for FSFB Iframe CKEditor 5 Plugin

# Schema del plugin CKEditor5 - DEBE coincidir exactamente con el ID del plugin
ckeditor5.plugin.fsfb_iframe_ckeditor_iframe_lazy:
  type: mapping
  label: 'FSFB Iframe Lazy Loading Plugin Configuration'
  mapping:
    enabled:
      type: boolean
      label: 'Enable iframe lazy loading'
    autoAdd:
      type: boolean
      label: 'Auto add iframe lazy loading'
    forceLazy:
      type: boolean
      label: 'Force iframe lazy loading'

# Schema del filtro de texto
filter.settings.fsfb_iframe_lazy_filter:
  type: mapping
  label: 'FSFB Iframe Lazy Loading Filter'
  mapping:
    status:
      type: boolean
      label: 'Enable filter'
    weight:
      type: integer
      label: 'Weight'
    settings:
      type: mapping
      label: 'Filter Settings'
      mapping: {}